### ISSUE TITLE
该项目可以改造成藏头诗吗？

### ISSUE THREAD

**Issue by limingyu1993** [THUNLP-AIPoet/WMPoetry#3]
藏头的内容在哪里指定呢？

**Comment by XiaoyuanYi** [comment]
@limingyu1993  你好，应该是可以的，但我们原本的模型里没有这一设计。您可以在我们的代码上进行改进。最简单的做法是在生成时直接将藏头的字指定为每句的首字，然后顺着首字进行生成。

**Comment by LukeChow** [comment]
> @limingyu1993 你好，应该是可以的，但我们原本的模型里没有这一设计。您可以在我们的代码上进行改进。最简单的做法是在生成时直接将藏头的字指定为每句的首字，然后顺着首字进行生成。

可以指点一下怎么指定为每句的首字吗？不胜感激！

**Comment by LukeChow** [comment]
@XiaoyuanYi 可以指点一下怎么指定为每句的首字吗？不胜感激！
