### ISSUE TITLE
训练模型时出现错误中断

### ISSUE THREAD

**Issue by suer112829** [THUNLP-AIPoet/WMPoetry#4]
训练完数据之后训练模型时出现如下错误，好像和第二个人提出的问题差不多，还是数据的问题吗，希望帮忙解决一下，万分感谢。
![问题1](https://user-images.githubusercontent.com/84113917/124283938-0c61d600-db7f-11eb-8c16-5e3467b2132c.png)

**Comment by My-captain** [comment]
@suer112829 同学您好，请问这个模型的size大概多少？3060单卡(12G)能跑嘛
